### ISSUE TITLE
Speed of Model

### ISSUE THREAD

**Issue by RWillisConger** [maartensap/riveter-nlp#10]
Hello! Apologies ahead of time, because I am new to Python and I'm 99.999% sure the issue is something obvious I'm doing wrong, not anything to do with the package.

I have 6 years of text data from a subreddit that I am trying to analyze, and the speed at which the package is running seems to be an issue. I've tried on Colab, and I've tried on my local computer. I've tried different formats (switching from a tokenized list of lists, so that each post was still differentiated, into a single undifferentiated string of text) and also tried just running smaller subsections of the data. The following screenshot is running on a single (tokenized) string of a little over 1,000 posts. I've run this subsection before, and it ended up taking about 8 hours and somehow failing along the way, so that when I woke up to check the model the next morning it was complete but blank. 

Is there something I can do differently? Thank you so much for your help with this!

<img width="1213" alt="Screenshot 2024-12-13 at 11 54 26 AM" src="https://github.com/user-attachments/assets/2aa20384-d32e-49c1-9c36-7c6950f92d7f" />

**Comment by maria-antoniak** [comment]
Hi, thanks for using Riveter! I don't think you're doing anything wrong, from what I can see 😊

Riveter is indeed slow because the first step is parsing all the texts, which is just always a costly procedure. 

I recommend batching your data and then combining the results at the end. This will require calling individual functions from Riveter, which I'm happy to help you with. For example, you could start by calling `__parse_and_extract` on all of your individual texts in batches and saving the outputs.

Or you could sample N posts per month and running on the smaller sample, at least at first. 

When running on Colab, it's possible that you're also running out space, given your dataset size, which might be causing your notebook to crash.

**Comment by RWillisConger** [comment]
Thank you so much for your prompt response! I've never batched data before, but I will give it a try. Is __parse_and_extract included in your documentation? I can't seem to find it.
<img width="1390" alt="Screenshot 2024-12-13 at 2 38 49 PM" src="https://github.com/user-attachments/assets/fe1163a4-75db-4d56-be5f-d3418934e568" />
This is my first attempt at batching, but with 90 seconds of processing time per 100 posts, and 271,000 total posts, I think that's still about 67 hours? But it is totally fair if this is outside your purview to discuss further, it's a data management issue rather than any problem with Riveter. Thank you!

**Comment by maria-antoniak** [comment]
No, it's not documented as normally you shouldn't need to call this function. You need to check the source code here: [https://github.com/maartensap/riveter-nlp/blob/main/riveter/riveter.py](https://github.com/maartensap/riveter-nlp/blob/main/riveter/riveter.py)

Yes, it might take a while. The goal is to save the output at each intermediate step so that you don't have to run the whole thing as one job, and if you have access to a cluster, you can distribute the jobs over many computers running in parallel (this would speed everything up a lot). Depending where you're working, you might have someone working in IT or managing the cluster who can help you with that part. But I'm happy to answer questions as you work through this!

**Comment by maria-antoniak** [comment]
Oh, just another idea. If there are specific entities that you're looking for, you could pre-filter your data to only include the posts with strings representing those entities. That might reduce your data size a lot!

**Comment by RWillisConger** [comment]
Thank you so much! This is really helpful, I will look into all of this
